version: v1


Agent:
  name: "agent-agni"
  domain: "agni.local"
  forward: 9000
  region: "global"
  certs: 'agni-agent/certs'
  Seeder:
    address: "localhost:8080"
    fingureprint: "86f7b7b55c1591c0aafbb9470baff92f1021791ca8f6ee9e372d0986a886be00"


Router:
  name: "agni-Router"
  router_ip: "127.0.0.1"
  rpc_port: "9000"
  proxy_port: "8000"
  certs: "agni-router/certmanger"
  region: "global"
  dns: "localhost"
  Seeder:
    address: "localhost:8080"
    fingureprint: "86f7b7b55c1591c0aafbb9470baff92f1021791ca8f6ee9e372d0986a886be00"
