version: v1


Agent:
  name: "agent-agni"
  domain: "agni.local"
  forward: 9000
  region: "global"
  certs: 'agni-agent/certs'
  registry:
    address: "localhost:8080"
    fingureprint: "86f7b7b55c1591c0aafbb9470baff92f1021791ca8f6ee9e372d0986a886be00"
