version: v1


Agent:
  name: "agent-agni"
  domain: "agni.local.internal"
  forward: 9000
  region: "global"
  certs: 'agni-agent/certs'
  Seeder:
    address: "localhost:8080"
    fingureprint: "84f141071957cd5f81a8650ab1e2b2f8f792091617611ad730bd7f3e134e9286"


Router:
  name: "agni-Router"
  router_ip: "127.0.0.1"
  rpc_port: "9000"
  proxy_port: "8000"
  certs: "agni-router/certmanger"
  region: "global"
  dns: "localhost"
  Seeder:
    address: "localhost:8080"
    fingureprint: "84f141071957cd5f81a8650ab1e2b2f8f792091617611ad730bd7f3e134e9286"


Nova:
  Seeder:
    address: "localhost:8080"
    fingureprint: "84f141071957cd5f81a8650ab1e2b2f8f792091617611ad730bd7f3e134e9286"